### ISSUE TITLE
Info about upcoming removal of packages in the General registry

### ISSUE THREAD

**Issue by KristofferC** [sorpaas/HTTP2.jl#6]
As described in https://discourse.julialang.org/t/ann-plans-for-removing-packages-that-do-not-yet-support-1-0-from-the-general-registry/ we are planning on removing packages that do not support 1.0 from the General registry. This package has been detected to not support 1.0 and is thus slated to be removed. The removal of packages from the registry will happen approximately a month after this issue is open.

To transition to the new Pkg system using `Project.toml`, see https://github.com/JuliaRegistries/Registrator.jl#transitioning-from-require-to-projecttoml.
To then tag a new version of the package, see https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app.

If you believe this package has erroneously been detected as not supporting 1.0 or have any other questions, don't hesitate to discuss it here or in the thread linked at the top of this post.

**Comment by PallHaraldsson** [comment]
While this package seems abandoned, I note there IS a PR to support 1.0: https://github.com/sorpaas/HTTP2.jl/pull/5

I didn't check, it may already work if merged (and I assume code for pre-1.0 works).

I not however a non-Julia approach through C code may be a better option to get working: https://github.com/JuliaWeb/HTTP.jl/issues/448 and HTTP2 (and HTTP3 which people may move to soon) seems too valuable a name to not use the fastest code out there.
